### PR TITLE
Correct version

### PR DESCRIPTION
**Pull request by JamesMcMahon**
The version string was never properly set for release 0.31.2.

Not sure the best way to handle this, but I figure I'd merge request it into develop and you could cherry pick into master if needed.

### CODE REVIEW

**Comment by JamesMcMahon** [comment]
This manifests in the auto updater thinking there is an update when you have the latest (0.31.2).

**Comment by chiuan** [comment]
i have download the 0.31.2.unity.zip
and delete the old Entitas folder, copy the newest to .
but the version is 0.31.1

**Comment by sschmid** [comment]
Ups, seems like I missed to update the version text file. I guess I was too excited to release a new version :) Thanks for letting me know. Screams for automation ;)

**Comment by JamesMcMahon** [comment]
Totally, I guess the horse is already out of the barn at this point 😄 🏇

**Pull request closed without merging**
