### PR TITLE
Safe execute method

### PR DESCRIPTION
**Pull request by Kaladrius2trip**

### CODE REVIEW

**Comment by sschmid** [comment]
Hi, thanks for you PR.
But I have to say that I think that this is a bad idea.
This change basically hides exceptions and doesn't fail. This will make it impossible to scale up your game. My motto: crash hard and early. Otherwise you cannot fix the actual bugs and you will have unexpected follow up errors that potentially doesn't have anything to do with the original exception.

There are use-cases where it's valid to silently catch exceptions, but not in the reactive system.

**Comment by Kaladrius2trip** [comment]
I have some problem in my project when i doesn't handle exception in some reactive system. 
But i have many exceptions in loop.
IMHO: Logs contain many EntityIsAlreadyRetainedByOwnerException errors but real useful information contains in first one from my code base. 
TryFinaly block hide only this exception in reactive system, but my error it still actual and i should see only one error but i saw more than expect. And i think any framework must be safe from a box. And my Exception it is my problem.

**Comment by sschmid** [comment]
Ah, I understand now. It's not catching the exception, it just prevents the followup exception `EntityIsAlreadyRetainedByOwnerException` not spam the console. I have to correct myself then, this is a good idea. Sorry, I initially though it's just catching the exception, which obviously wouldn't be such a great idea.
Thanks for clearing things up! 👍 
Will be in the next release

**Comment by Kaladrius2trip** [comment]
Thanks for you work!

**Comment by optimisez** [comment]
@sschmid Is that possible to implement this similar feature without using any Exception Handling statements (try-finally for this PR)? From what I understand, it will have performance penalty when using Exception Handling statements.

**Comment by Kaladrius2trip** [comment]
@optimisez It low cost operation. For my project thar solve many problem for debugging and handle exception. In the world-wide we may find many tests for using try-finally blocks. 
[For example stackoverflow.com](https://stackoverflow.com/questions/4106891/overhead-of-try-finally-in-c)

**Pull request merged**
