### PR TITLE
Added more tests and fixes for entity reference counting

### PR DESCRIPTION
**Pull request by mzaks**

### CODE REVIEW

**Comment by sschmid** [comment]
Hi, thanks. Please pull b306d8f612b87700da6862d3f6f54c3bc80e0947 from https://github.com/sschmid/Entitas-CSharp/tree/mzaks-develop, i marked lines of code in ReactiveSystem that are missing tests. Could you test for that too, please :)

**Comment by mzaks** [comment]
Ops I see there is a bug. I will fix it today. Please don't merge.

**Comment by sschmid** [comment]
Shall I merge now?

**Comment by JuDelCo** [comment]
You shall not until your tests pass

**Comment by sschmid** [comment]
Haha :)

**Pull request merged**
