### PR TITLE
Add ITypeDrawer for doubles, support visual debugging of enum masks

### PR DESCRIPTION
**Pull request by bddckr**

### CODE REVIEW

**Comment by sschmid** [comment]
Hey, awesome! Thanks for contributing. Could you do me a favour. I merged your changes into develop and added MyDoubleComponent and MyFlagsComponent to the VisualDebugging project to test if it's working.
I added Item2 as a start value, but the drawer shows Item1.
https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas.Unity/Assets/Examples/VisualDebugging/VisualDebuggingExampleController.cs#L36

Would be great if you could look into this!

**Comment by bddckr** [comment]
You have to make sure the enum constants are a power of two, also you should add a `None` enum constant:

```c#
[System.Flags]
public enum MyFlags {
    None = 0,
    Item1 = 1 << 0,
    Item2 = 1 << 1,
    Item3 = 1 << 2
}
```

See [the `FlagsAttribute` docs](https://msdn.microsoft.com/en-us/library/system.flagsattribute(v=vs.110).aspx) and [this stackoverflow answer](http://stackoverflow.com/a/8480) for more info.

**Comment by bddckr** [comment]
Just tested with my changes mentioned above... Still getting _Item 1_. :confused:

**Comment by bddckr** [comment]
Found it! If you remove the None constant above everything works.

As soon as there is a constant with value 0 everything is off by one. [This is a bug in EnumMaskField.](https://community.unity.com/t5/Documentation/EditorGUILayout-EnumMaskField-can-invent-values-for-your-enum/td-p/2531847)

**Comment by sschmid** [comment]
Ok, cool! Thanks

**Pull request merged**
