### PR TITLE
Added support for TypeToInt() generation in IndicesLookup code.

### PR DESCRIPTION
**Pull request by gjroelofs**

### CODE REVIEW

**Comment by gjroelofs** [comment]
Testcases are not passing, and hard to fix due to platform-specific build settings.

**Comment by sschmid** [comment]
What do you mean with "platform-specific build settings"?

**Comment by gjroelofs** [comment]
The generated code is compared directly to an @"" created string without unifying the line-endings.
On a Windows environment I'm getting errors on all ComponentExtension and IndicesLookupGenerator testcases because CL/+RF are used intermixed in the generation code.

Getting VS to function properly with line-endings is a known head-ache, so I'd suggest unifying the line-endings before comparison (or making the comparison line-ending agnostic).

Some of the errors I get locally on develop after a VS compile:

Expected string length 1073 but was 1068. Strings differ at index 19., Expected: "namespace Entitas {\r\n public partial class Entity {\r\n ...", But was: "namespace Entitas {\n public partial class Entity {\n ...", -------------------------------^
   at describe_ComponentExtensionsGenerator.generates(Type type, String code) in D:\Projects\C#\Libraries\Entitas\Tests\
Tests\Entitas.CodeGenerator\describe_ComponentExtensionsGenerator.cs:line 25
   at describe_ComponentExtensionsGenerator.<when_generating>b__3_0() in D:\Projects\C#\Libraries\Entitas\Tests\Tests\En
titas.CodeGenerator\describe_ComponentExtensionsGenerator.cs:line 29

**Comment by sschmid** [comment]
I see, will try to get a windows machine and fix that!

**Comment by sschmid** [comment]
Type to int can be achieved with
```
Array.IndexOf(ComponentIds.componentTypes, myType);
```

**Pull request closed without merging**
