### PR TITLE
Rename pool to context

### LINKED ISSUE #99: Pool vs Context
Hey guys, this is more or less a poll:
What do you guys actually think of the name Pool? I was thinking calling it Context instead of Pool. I started thinking that it might be a better name since we often use it to spilt our games into different 'contexts' like Core, Meta, UI

Let me know what you think, maybe you have even better suggestions...

### PR DESCRIPTION
**Pull request by sschmid**
Closes #99

### CODE REVIEW

**Comment by 7ujian** [comment]
@sschmid it's would be great to mention in getting start docs about the Pool to Context change.

**Comment by Propolandante** [comment]
@7ujian As a brand new user, I agree. I read the wiki thoroughly and dissected the Asteroids example project, but then immediately felt lost when one of the core pillars of Entitas wasn't functioning at all.

**Comment by shawnfromportland** [comment]
I hope to contribute to the documentation as soon as both i understand the existing documentation perfectly and have the time. in the following months perhaps.

**Comment by sschmid** [comment]
@Propolandante I know that the docs and wiki are behind atm. In the last weeks / months I did a rather big change to the code base and I'm currently preparing for the next release. So I'm currently really busy with the code base. Once I'm done I try to update the wiki. In the meantime I try to as transparent as I can by sharing my current progress with issues / pull request / chat announcements so you guys have the chance to follow whats happening.

**Comment by JuDelCo** [comment]
Do you have a date ? It's okay if you can't say one / don't know, I'm not in hurry, only wondering :)

**Comment by sschmid** [comment]
@JuDelCo 
I'm currently writing a new migration assistant to make things easier. the version itself is ready. bleeding edge is on develop. Also testing maxims dsl. I don't wanna rush the release and try to make upgrading less a pain. ETA: this month

**Comment by JuDelCo** [comment]
Okay thanks ! ;)

**Pull request merged**
