### PR TITLE
Generate EntityIndex Closes #75

### LINKED ISSUE #75: Generate EntityIndex
Generate Indexer class for fast lookups for fields in components tagged with [IndexKey]

``` cs
public class NameComponent {
  [IndexKey]
  public string value;
}

var entity = pool.GetEntityWithNameValue("Player1");
```

### PR DESCRIPTION
**Pull request by sschmid**
EntityIndex let's you access entities with a certain key immediately.
For example: You have 1000000 entities with NameComponent, you can create an EntityIndex and get an entity with a name "Max" in constant time
```csharp
var index = new EntityIndex<string>(group, c => ((NameComponent)c).value);
// This returns the entity immediately
index.GetEntity("Max");
```
without iterating over the entities like
```csharp
// This might take veeeery long
entities.Where(e => e.name.value == "Max");
```

Update the code generator to generate EntityIndex for you, so you don't have to create it manually.

Idea:
```csharp
public class NameComponent : IComponent {

    // This attribute will make the code generator create an EntityIndex for you
    // and generate some methods for the pool
    [IndexKey("UserName")]
    public string name;
}
```

```csharp

// How convenient :)
// And so fast
pool.GetEntityWithUserName("Max);
```

Works with any kind of key
```csharp
pool.GetEntityWithPosition(Vector3.zero);
```

### CODE REVIEW

**Comment by JuDelCo** [comment]
Wow, looks like a great addition to the framework

I will see how this works behind the scene... :smile:

**Comment by JuDelCo** [comment]
Mmm, if you deactivate a EntityIndex (or all of them), you can't reactivate it (as the suscriber code is in the constructor). So why not destruct/remove it instead ?

(Btw, "This returns the entity immediately", well... as fast as a Dictionary key lookup can :smile: )

**Comment by JuDelCo** [comment]
Also, if you add an EntityIndex to a group that has already entities, those won't be stored as keys in the index Dictionary

**Comment by sschmid** [comment]
Atm there is no Activate() by design. You remove them from the array in the pool?

"immediately" as in
Performance Test
Before: 200ms
After: 0ms

Which is kind of immediately ;) Yes, it's basically a dictionary lookup

**Comment by sschmid** [comment]
Yes, I though of that, too. Will be implemented.
Great to see that you're looking at it closely :)

**Pull request merged**
