### PR TITLE
Blueprints

### PR DESCRIPTION
**Pull request by sschmid**
Playing around with Blueprints to get a feel for it

### CODE REVIEW

**Comment by sschmid** [comment]
```
var player = new ComponentBlueprint(24, "PlayerComponent", null);

var positionFields = new Dictionary<string, object> {
    { "x", 12 }, { "y", 34 }, { "z", 56 }
};
var position = new ComponentBlueprint(42, "PositionComponent", positionFields);

var components = new [] {
    player,
    position
};

var blueprint = new Blueprint(string.Empty, components);

pool.CreateEntity(blueprint);
```

**Comment by sschmid** [comment]
Blueprints contain all the information needed to create an entity. We can add converters to create Blueprints from different sources like XML, JSON, YAML, etc. We can either use them directly with `pool.CreateEntity(blueprint)` or use them as a base for code generation `pool.CreateHero()`

The first approach relies on reflection and might be slower than the code generation approach where no reflection is necessary.

**Comment by npruehs** [comment]
Had to look a short while before I found `Pool.CreateEntity(Blueprint)` and `ComponentBlueprint.CreateComponent()`, but yeah, this seems to be exactly the way we're doing it in our framework as well. Nice! :)

**Comment by sschmid** [comment]
Blueprints are not in yet. The branch has been merged, but the contents have been removed again. I'll create a new branch once I continue working on this feature.

**Pull request merged**
