### PR TITLE
Added List property on Pools generation, including updated testcase.

### PR DESCRIPTION
**Pull request by gjroelofs**

### CODE REVIEW

**Comment by chrischu** [comment]
List is probably not the appropriate type since (at least from my perspective) it should not be possible to add a pool from the outside. 

You should probably change the List<Pool> to ReadOnlyCollection<T>.

**Comment by gjroelofs** [comment]
Agreed, I cached the result now was well (and changed the internal pool naming to avoid conflicts).

**Comment by sschmid** [comment]
PoolsGenerator generates Pools.allPools now.

**Comment by gjroelofs** [comment]
Just a heads up, if you now declare a Pool named "allPools", you'll create compile errors. See 631b497

**Pull request closed without merging**
